//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public int Id_Product { get; set; }
        public int Id_Customer { get; set; }
        public int Id_Stuff { get; set; }
        public int Num { get; set; }
        public System.DateTime Date { get; set; }
        public int SumPrice { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Products Products { get; set; }
        public virtual Stuff Stuff { get; set; }
    }
}
